name: CI

on:
  pull_request:
    branches:
      - main
    paths:
      - 'packages/**'
  workflow_dispatch:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 23.x]
    steps:
      # Checkout the repository
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Install pnpm
      - uses: pnpm/action-setup@v4

      # Cache node_modules
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      # Setup .npmrc file to publish to npm
      - run: |
          echo "registry=https://registry.npmjs.org/" > ~/.npmrc
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" >> ~/.npmrc

      # Install dependencies
      - run: pnpm install --frozen-lockfile
      - uses: nrwl/nx-set-shas@v4

      # Detect affected projects
      - name: Detect Affected Projects
        id: detect-projects
        run: |
          # Find changes in packages directory
          affected_dirs=$(git diff --name-only HEAD~1 HEAD | grep '^packages/' | cut -d '/' -f 2 | sort | uniq | xargs)

          # Handle empty results
          if [ -z "$affected_dirs" ]; then
          echo "No affected projects found."
          echo "affected_projects=[]" >> $GITHUB_ENV
          exit 0
          fi

          # Sanitize and convert to JSON array for GitHub Actions
          affected_json=$(echo "$affected_dirs" | tr ' ' '\n' | jq -R . | jq -s . | tr -d '\n' | tr -d '\r')
          echo "Affected Projects: $affected_json"
          echo "affected_projects=$affected_json" >> $GITHUB_ENV

      # Run CI for each affected project
      - name: Run CI
        if: env.affected_projects != '[]'
        run: |
          echo "Affected Projects: ${{ env.affected_projects }}"
          for project in $(echo "${{ env.affected_projects }}" | jq -r '.[]'); do
            echo "Running CI for project: $project"
            pnpm exec nx run "$project:ci"
          done
