name: CI

on:
  pull_request:
    branches:
      - main
    paths:
      - 'packages/**'
  workflow_dispatch:

permissions:
  actions: read
  contents: read

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v42
        with:
          files: packages/**
          json: true

      - name: Set matrix
        id: set-matrix
        run: |
          CHANGES=$(echo ${{ steps.changed-files.outputs.all_changed_files }} | jq -c '
            map(
              capture("^packages/(?<package>[^/]+)").package
            ) |
            unique
          ')
          echo "matrix=${CHANGES}" >> $GITHUB_OUTPUT

  main:
    needs: detect-changes
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 23.x]
    steps:
      # Checkout the repository
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Install pnpm
      - uses: pnpm/action-setup@v4

      # Cache node_modules
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      # Setup .npmrc file to publish to npm
      - run: |
          echo "registry=https://registry.npmjs.org/" > ~/.npmrc
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" >> ~/.npmrc

      # Install dependencies
      - run: pnpm install --frozen-lockfile
      - uses: nrwl/nx-set-shas@v4

      # Run package-specific CI for changed packages
      - name: Run project CI
        if: needs.detect-changes.outputs.matrix != '[]'
        run: |
          echo '${{needs.detect-changes.outputs.matrix}}' | jq -r '.[]' | while read project; do
            echo "Running CI for packages/$project"
            pnpm exec nx run $project:ci
          done
